### ISSUE TITLE
Integrate Firebase Adming SDK

### ISSUE THREAD

**Issue by dylanherbig** [hoohacks/hack-x#1]
We would like to be able to utilize the Hack-X system as an admin as well. As such, we will utilize the Firebase Admin SDK as a tool to assign user roles, and to also help with managing database queries with proper credentials:

- FirebaseAdminConfig.ts already includes configuration for admin sdk
- Ensure that all imports work properly 
- Test the functionality of the Admin SDK by creating an admin user and by calling a function 
- If necessary, update securization settings within Firebase, but make sure to document them here and by creating a README

**Comment by Akhil-Desai** [comment]
I was able to sign-up using the Admin password, but I'm unsure on how to check whether I received the admin persmissions. As in like what functions would I be able to call

**Comment by dylanherbig** [comment]
@Akhil-Desai please push your code and i will be able to double check if it works or not properly
