### ISSUE TITLE
Send email verification using the Firebase Auth platform

### ISSUE THREAD

**Issue by dylanherbig** [hoohacks/hack-x#2]
As new users sign-up for our platform, we require them to validate their email. As of now, I believe that it would be best to use the Firebase Auth generic email template to validate them. Integrate and test this feature please. Use this [documentation](https://firebase.google.com/docs/auth/web/manage-users) as guideline

**Comment by eduardocis** [comment]
i will take this one

**Comment by dylanherbig** [comment]
push your code @eduardocis
