### ISSUE TITLE
Create a generic User collection within Firestore

### ISSUE THREAD

**Issue by dylanherbig** [hoohacks/hack-x#3]
From now on we will utilize the NO SQL database solution from Google called Firestore. Please read up on it [here ](https://firebase.google.com/docs/firestore). It utilizes collections to manage date. Please create a user collection based on the UML diagram that is linked below and ensure that when a user is registered that a user is also created within the Firestore database 

--> password might not be necessary since it is handled by Firebase auth

![Image](https://github.com/hoohacks/hack-x/assets/83849210/2a08f7f2-50fc-4a1a-829c-2c52df880ccd)

**Comment by Akhil-Desai** [comment]
I can take this one

**Comment by eduardocis** [comment]
bro plz
